class CopilotSignals {
  constructor(){this.rows=[];this.charts={};this.tableSort={key:'generation',direction:'desc'};this.breakdownDim='model';this.seatFilter='all';this.bind()}
  bind(){
    document.querySelector('#fileInput').addEventListener('change',e=>this.loadFiles([...e.target.files]));
    document.querySelector('#loadSample').addEventListener('click',()=>this.loadSample());
    ['dateFilter','userFilter','modelFilter'].forEach(id=>document.querySelector('#'+id).addEventListener('change',()=>this.render()));
    document.querySelector('#resetFilters').addEventListener('click',()=>{['dateFilter','userFilter','modelFilter'].forEach(id=>document.querySelector('#'+id).value='all');this.render()});
    document.querySelector('#tableSearch').addEventListener('input',()=>this.renderTable(this.filtered()));
    document.querySelectorAll('.sortable').forEach(th=>th.addEventListener('click',()=>this.sortTable(th.dataset.sort)));
    document.querySelectorAll('#breakdownToggle .dim-btn').forEach(b=>b.addEventListener('click',()=>{this.breakdownDim=b.dataset.dim;document.querySelectorAll('#breakdownToggle .dim-btn').forEach(x=>x.classList.toggle('active',x===b));this.render()}));
    document.querySelectorAll('#seatFilterToggle .dim-btn').forEach(b=>b.addEventListener('click',()=>{this.seatFilter=b.dataset.seat;document.querySelectorAll('#seatFilterToggle .dim-btn').forEach(x=>x.classList.toggle('active',x===b));this.renderTable(this.filtered())}));
  }
  async loadSample(){try{const r=await fetch('./data_example.json');if(!r.ok)throw Error();this.ingest(this.parseText(await r.text(),'data_example.json'))}catch{this.toast('Could not load the included sample. Try serving this folder locally.')}}
  async loadFiles(files){try{this.ingest((await Promise.all(files.map(async f=>this.parseText(await f.text(),f.name)))).flat())}catch(e){console.error(e);this.toast('That file could not be read as a Copilot export.')}}
  parseText(text){const clean=text.replace(/^\uFEFF/,'').trim();if(!clean)return [];try{const parsed=JSON.parse(clean);return Array.isArray(parsed)?parsed:(parsed.data||parsed.rows||[parsed])}catch{try{return clean.split(/\r?\n/).filter(Boolean).map(JSON.parse)}catch{throw Error('Invalid JSON')}}}
  ingest(rows){this.rows=rows.filter(r=>r&&r.day&&(r.user_login||r.User));if(!this.rows.length)throw Error('No records');this.populateFilters();document.querySelector('#uploadPanel').hidden=true;document.querySelector('#dashboard').hidden=false;this.render();this.toast(`${this.rows.length.toLocaleString()} daily records loaded`)}
  populateFilters(){this.populate('userFilter',new Set(this.rows.map(r=>this.user(r))),'Everyone');this.populate('modelFilter',new Set(this.rows.flatMap(r=>(r.totals_by_model_feature||[]).map(x=>x.model)).filter(Boolean)),'All models')}
  populate(id,values,label){const s=document.querySelector('#'+id),previous=s.value;s.innerHTML=`<option value="all">${label}</option>`+[...values].sort().map(v=>`<option value="${this.escape(v)}">${this.escape(v)}</option>`).join('');s.value=[...s.options].some(o=>o.value===previous)?previous:'all'}
  user(r){return r.user_login||r.User}
  selected(){return document.querySelector('#modelFilter').value}
  filtered(){const max=this.rows.reduce((a,r)=>a>r.day?a:r.day,'');const days=+document.querySelector('#dateFilter').value;const since=days?new Date(new Date(max+'T00:00:00Z').getTime()-(days-1)*864e5).toISOString().slice(0,10):'';const user=document.querySelector('#userFilter').value,model=this.selected();return this.rows.filter(r=>(!since||r.day>=since)&&(user==='all'||this.user(r)===user)&&(model==='all'||(r.totals_by_model_feature||[]).some(x=>x.model===model)))}
  activity(r){return(+r.user_initiated_interaction_count||0)+(+r.code_generation_activity_count||0)+(+r.code_acceptance_activity_count||0)}
  breakdown(rows,key,dimension,metric='code_generation_activity_count'){const out={},model=this.selected();rows.forEach(r=>(r[key]||[]).forEach(x=>{if(x[dimension]&&(dimension!=='model'||model==='all'||x.model===model))out[x[dimension]]=(out[x[dimension]]||0)+(+x[metric]||0)}));return out}
  render(){
    const rows=this.filtered(),active=rows.filter(r=>this.activity(r)>0),allUsers=new Set(this.rows.map(r=>this.user(r))).size,reported=new Set(rows.map(r=>this.user(r))).size,activeUsers=new Set(active.map(r=>this.user(r))).size,sum=k=>rows.reduce((n,r)=>n+(+r[k]||0),0),pct=(a,b)=>b?`${Math.round(a/b*100)}%`:'—';
    const agentUsers=new Set(active.filter(r=>r.used_agent).map(r=>this.user(r))).size,chatUsers=new Set(active.filter(r=>r.used_chat).map(r=>this.user(r))).size;
    this.set('activeUsers',activeUsers.toLocaleString());this.set('activeUsersNote',`${reported.toLocaleString()} reported in selection · ${allUsers.toLocaleString()} in export`);this.set('engagementRate',pct(activeUsers,reported));this.set('agentRate',pct(agentUsers,activeUsers));this.set('agentNote',`${agentUsers.toLocaleString()} active people`);this.set('chatRate',pct(chatUsers,activeUsers));this.set('acceptedCode',sum('code_acceptance_activity_count').toLocaleString());this.set('acceptedNote',`${sum('loc_added_sum').toLocaleString()} lines added after Copilot activity`);this.set('creditsUsed',this.format(sum('ai_credits_used')));const dormantCount=reported-activeUsers;this.set('dormantSeats',dormantCount.toLocaleString());this.set('dormantNote',`${pct(dormantCount,reported)} of reported seats`);
    const features=this.breakdown(rows,'totals_by_feature','feature','user_initiated_interaction_count'),routing={Agent:{auto:0,named:0},Ask:{auto:0,named:0}},byDay={};
    rows.forEach(r=>{const d=byDay[r.day]||={interactions:0,generation:0,auto:0,named:0};d.interactions+=+r.user_initiated_interaction_count||0;d.generation+=+r.code_generation_activity_count||0;(r.totals_by_model_feature||[]).forEach(m=>{if(this.selected()!=='all'&&m.model!==this.selected())return;const amount=+m.code_generation_activity_count||0;const type=m.model==='auto'?'auto':'named';d[type]+=amount;const mode=m.feature?.includes('agent')?'Agent':m.feature?.includes('ask')?'Ask':null;if(mode)routing[mode][type]+=amount});byDay[r.day]=d});
    const share=mode=>{const r=routing[mode];return r.auto+r.named?Math.round(r.auto/(r.auto+r.named)*100):null},agentAuto=share('Agent'),askAuto=share('Ask');this.set('autoRate',agentAuto===null&&askAuto===null?'No model activity':`Agent ${agentAuto??'—'}% · Ask ${askAuto??'—'}%`);this.set('autoNarrative','Auto share of model-attributed code generation. The comparison excludes features without an Agent or Ask mode label.');
    const ds=Object.keys(byDay).sort(),mid=Math.ceil(ds.length/2),early=ds.slice(0,mid).reduce((n,d)=>n+byDay[d].interactions,0),late=ds.slice(mid).reduce((n,d)=>n+byDay[d].interactions,0),change=early?Math.round((late-early)/early*100):0,top=this.top(features);this.set('momentum',ds.length?`${change>=0?'+':''}${change}% interactions`:'—');this.set('momentumNarrative','Comparing the later half of the selected period with the earlier half.');this.set('workflow',top?this.label(top[0]):'—');this.set('workflowNarrative',top?`${this.format(top[1])} user-initiated interactions in the leading Copilot feature.`:'No feature activity was reported.');
    this.chart('activityChart','line',{labels:ds,datasets:[{label:'Interactions',data:ds.map(d=>byDay[d].interactions),borderColor:'#83f1c5',backgroundColor:'#83f1c522',fill:true,tension:.35},{label:'Code generation',data:ds.map(d=>byDay[d].generation),borderColor:'#7da8ff',tension:.35}]});
    this.chart('routingTrendChart','stackedBar',{labels:ds,datasets:[{label:'Auto',data:ds.map(d=>byDay[d].auto),backgroundColor:'#ffb86b'},{label:'Named models',data:ds.map(d=>byDay[d].named),backgroundColor:'#e69cff'}]});
    this.chart('modeRoutingChart','multiBar',{labels:['Agent workflows','Ask mode'],datasets:[{label:'Auto',data:[agentAuto||0,askAuto||0],backgroundColor:'#ffb86b'},{label:'Named models',data:[agentAuto===null?0:100-agentAuto,askAuto===null?0:100-askAuto],backgroundColor:'#e69cff'}]});
    const people=this.people(rows),repeat={'One day':0,'Occasional (2–5)':0,'Sustained (6+)':0};Object.values(people).filter(p=>p.active).forEach(p=>repeat[p.days===1?'One day':p.days<=5?'Occasional (2–5)':'Sustained (6+)']++);this.chart('repeatUseChart','bar',{labels:Object.keys(repeat),values:Object.values(repeat)});
    const breakdownSources={model:['totals_by_model_feature','model','code_generation_activity_count'],feature:['totals_by_feature','feature','user_initiated_interaction_count'],language:['totals_by_language_feature','language','code_generation_activity_count']},[bKey,bDim,bMetric]=breakdownSources[this.breakdownDim];
    this.chart('breakdownChart','bar',this.topN(this.breakdown(rows,bKey,bDim,bMetric)));
    this.chart('ideChart','bar',this.topN(this.breakdown(rows,'totals_by_ide','ide','user_initiated_interaction_count')));
    const locPeople=Object.entries(people).filter(([,p])=>p.agentLoc+p.userLoc>0).sort((a,b)=>(b[1].agentLoc+b[1].userLoc)-(a[1].agentLoc+a[1].userLoc)).slice(0,12),agentLocTotal=Object.values(people).reduce((n,p)=>n+p.agentLoc,0),userLocTotal=Object.values(people).reduce((n,p)=>n+p.userLoc,0);
    this.chart('locChart','stackedBarH',{labels:locPeople.map(x=>x[0]),datasets:[{label:'Agent-initiated',data:locPeople.map(x=>x[1].agentLoc),backgroundColor:'#7da8ff'},{label:'User-initiated',data:locPeople.map(x=>x[1].userLoc),backgroundColor:'#83f1c5'}]});
    this.set('agentContributionNote',agentLocTotal+userLocTotal?`${pct(agentLocTotal,agentLocTotal+userLocTotal)} agent-initiated org-wide`:'No LOC activity');
    const surfaces={Chat:new Set(),Agent:new Set(),CLI:new Set(),'Coding agent':new Set(),'Cloud agent':new Set(),'Copilot app':new Set()};active.forEach(r=>{const u=this.user(r);if(r.used_chat)surfaces.Chat.add(u);if(r.used_agent)surfaces.Agent.add(u);if(r.used_cli)surfaces.CLI.add(u);if(r.used_copilot_coding_agent)surfaces['Coding agent'].add(u);if(r.used_copilot_cloud_agent)surfaces['Cloud agent'].add(u);if(r.used_copilot_app)surfaces['Copilot app'].add(u)});this.chart('surfaceChart','bar',{labels:Object.keys(surfaces),values:Object.values(surfaces).map(s=>s.size)});this.chart('peopleChart','bar',this.topN(Object.fromEntries(Object.entries(people).map(([u,p])=>[u,p.interactions])),12));this.renderTable(rows);this.set('reportTitle','Copilot activity');this.set('reportMeta',ds.length?`${ds[0]} – ${ds.at(-1)} · ${rows.length.toLocaleString()} user/day records`:'No records match these filters');
  }
  people(rows){const people={},lastActive={};this.rows.forEach(r=>{if(this.activity(r)>0){const u=this.user(r);if(!lastActive[u]||r.day>lastActive[u])lastActive[u]=r.day}});const maxDay=this.rows.reduce((a,r)=>a>r.day?a:r.day,'');rows.forEach(r=>{const u=this.user(r),p=people[u]||={days:0,interactions:0,generation:0,accepted:0,credits:0,chatInteractions:0,agentLoc:0,userLoc:0,compShown:0,compAccepted:0,agent:false,chat:false,active:false};p.days++;p.interactions+=+r.user_initiated_interaction_count||0;p.generation+=+r.code_generation_activity_count||0;p.accepted+=+r.code_acceptance_activity_count||0;p.credits+=+r.ai_credits_used||0;p.agent||=!!r.used_agent;p.chat||=!!r.used_chat;p.active||=this.activity(r)>0;(r.totals_by_feature||[]).forEach(f=>{if(f.feature?.includes('chat'))p.chatInteractions+=+f.user_initiated_interaction_count||0;const loc=(+f.loc_added_sum||0)+(+f.loc_deleted_sum||0);if(/agent|edit|custom/i.test(f.feature||''))p.agentLoc+=loc;else p.userLoc+=loc;if(f.feature==='code_completion'){p.compShown+=+f.code_generation_activity_count||0;p.compAccepted+=+f.code_acceptance_activity_count||0}});people[u]=p});Object.values(people).forEach(p=>p.acceptRate=p.compShown?p.compAccepted/p.compShown*100:-1);Object.entries(people).forEach(([u,p])=>{p.lastActive=lastActive[u]||null;p.idleDays=p.lastActive?Math.round((new Date(maxDay)-new Date(p.lastActive))/864e5):Infinity});return people}
  sortTable(key){this.tableSort={key,direction:this.tableSort.key===key&&this.tableSort.direction==='desc'?'asc':'desc'};this.renderTable(this.filtered())}
  renderTable(rows){const query=document.querySelector('#tableSearch').value.toLowerCase(),people=this.people(rows),{key,direction}=this.tableSort,seat=this.seatFilter;document.querySelectorAll('.sortable').forEach(th=>th.querySelector('.sort-indicator').textContent=th.dataset.sort===key?(direction==='desc'?'↓':'↑'):'↕');document.querySelector('#peopleTable').innerHTML=Object.entries(people).filter(([u,p])=>u.toLowerCase().includes(query)&&(seat==='all'||(seat==='active'?p.active:!p.active))).sort((a,b)=>key==='name'?direction==='asc'?a[0].localeCompare(b[0]):b[0].localeCompare(a[0]):(direction==='asc'?1:-1)*((key==='agent'||key==='chat'?(a[1][key]?1:0):a[1][key])-(key==='agent'||key==='chat'?(b[1][key]?1:0):b[1][key]))).map(([u,p])=>`<tr><td>${this.escape(u)}</td><td>${p.days}</td><td>${p.lastActive?`${p.lastActive} (${p.idleDays}d ago)`:'Never'}</td><td>${this.format(p.interactions)}</td><td>${this.format(p.generation)}</td><td>${this.format(p.accepted)}</td><td>${p.acceptRate>=0?Math.round(p.acceptRate)+'%':'—'}</td><td><span class="badge ${p.agent?'on':''}">${p.agent?'Used':'—'}</span></td><td><span class="badge ${p.chat?'on':''}">${p.chat?'Used':'—'}</span></td><td>${this.format(p.credits)}</td></tr>`).join('')||'<tr><td colspan="10">No people match the current filters.</td></tr>'}
  chart(id,type,data){if(this.charts[id])this.charts[id].destroy();const canvas=document.querySelector('#'+id);let config;if(type==='line')config={type,data,options:this.options(false,true)};else if(type==='stackedBar'||type==='stackedBarH'){config={type:'bar',data,options:this.options(false,true)};config.options.scales.x.stacked=true;config.options.scales.y.stacked=true;if(type==='stackedBarH')config.options.indexAxis='y'}else if(type==='multiBar')config={type:'bar',data,options:this.options(false,true)};else{const labels=data.labels||[],values=data.values||[];config={type,data:{labels,datasets:[{data:values,backgroundColor:['#83f1c5','#7da8ff','#e69cff','#ffb86b','#61d6ed','#a4b5ff','#ff8ea1','#b5d77a','#d7a7ff','#f2d68c','#80c5ad','#eaa3c1']}]},options:this.options(type==='doughnut')};if(type==='bar')config.options.indexAxis='y'}this.charts[id]=new Chart(canvas,config)}
  options(donut,legend=donut){return {responsive:true,maintainAspectRatio:true,plugins:{legend:{display:legend,labels:{color:'#b9c6d9',boxWidth:10,font:{size:11}}},tooltip:{callbacks:{label:c=>`${c.label||c.dataset.label}: ${this.format(c.raw??c.parsed.y??c.parsed)}`}}},scales:donut?{}:{x:{ticks:{color:'#8ea0b9',maxRotation:0,autoSkip:true},grid:{color:'#20304a'}},y:{ticks:{color:'#8ea0b9'},grid:{color:'#20304a'},beginAtZero:true}}}}
  top(o){return Object.entries(o).sort((a,b)=>b[1]-a[1])[0]} topN(o,n=8){const a=Object.entries(o).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,n);return {labels:a.map(x=>this.label(x[0])),values:a.map(x=>x[1])}} label(s){return String(s).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())} set(id,v){document.querySelector('#'+id).textContent=v} format(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:1})} escape(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML} toast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
}
document.addEventListener('DOMContentLoaded',()=>new CopilotSignals());
