/* GitHub Copilot activity export viewer. Handles NDJSON, JSON arrays, and legacy CSV. */
class CopilotSignals {
  constructor() { this.rows=[]; this.charts={}; this.bind(); }
  bind() {
    document.querySelector('#fileInput').addEventListener('change', e => this.loadFiles([...e.target.files]));
    document.querySelector('#loadSample').addEventListener('click', () => this.loadSample());
    ['dateFilter','userFilter','modelFilter'].forEach(id => document.querySelector('#'+id).addEventListener('change', () => this.render()));
    document.querySelector('#resetFilters').addEventListener('click', () => { ['dateFilter','userFilter','modelFilter'].forEach(id => document.querySelector('#'+id).value='all'); this.render(); });
    document.querySelector('#tableSearch').addEventListener('input', () => this.renderTable(this.filtered()));
  }
  async loadSample() { try { const r=await fetch('./part-00245-9f344339-d354-4680-95f3-7cffacce7ad3.c000.ndjson'); if(!r.ok) throw Error(); this.ingest(this.parseText(await r.text(), 'sample.ndjson')); } catch { this.toast('Could not load the included sample. Try serving this folder locally.'); } }
  async loadFiles(files) { try { const all=(await Promise.all(files.map(async f=>this.parseText(await f.text(),f.name)))).flat(); this.ingest(all); } catch(e) { console.error(e); this.toast('That file could not be read as a Copilot export.'); } }
  parseText(text,name) { const clean=text.replace(/^\uFEFF/,'').trim(); if(!clean) return []; if(name.toLowerCase().endsWith('.csv')) return this.parseLegacyCsv(clean); try { const parsed=JSON.parse(clean); return Array.isArray(parsed)?parsed:(parsed.data||parsed.rows||[parsed]); } catch { try { return clean.split(/\r?\n/).filter(Boolean).map(JSON.parse); } catch { throw Error('Invalid JSON'); } } }
  parseLegacyCsv(text) { const lines=text.split(/\r?\n/), heads=lines.shift().split(','); return lines.filter(Boolean).map(line=>{const v=line.split(',');const x=Object.fromEntries(heads.map((h,i)=>[h,v[i]]));return {day:(x.Timestamp||'').slice(0,10),user_login:x.User,user_initiated_interaction_count:+x['Requests Used']||0,code_generation_activity_count:+x['Requests Used']||0,code_acceptance_activity_count:0,totals_by_model_feature:[{model:x.Model||'unknown',feature:'legacy_premium_request',code_generation_activity_count:+x['Requests Used']||0}],totals_by_feature:[],totals_by_language_feature:[],totals_by_ide:[],used_agent:false,used_chat:false,ai_credits_used:0};}); }
  ingest(rows) { this.rows=rows.filter(r=>r && r.day && (r.user_login || r.User)); if(!this.rows.length) throw Error('No records'); this.populateFilters(); document.querySelector('#uploadPanel').hidden=true; document.querySelector('#dashboard').hidden=false; this.render(); this.toast(`${this.rows.length.toLocaleString()} daily records loaded`); }
  populateFilters() { const opts=(id,vals,label)=>{const s=document.querySelector('#'+id),current=s.value;s.innerHTML=`<option value="all">${label}</option>`+[...vals].sort().map(x=>`<option value="${this.escape(x)}">${this.escape(x)}</option>`).join('');s.value=[...s.options].some(o=>o.value===current)?current:'all';};opts('userFilter',new Set(this.rows.map(r=>r.user_login||r.User)),'Everyone');opts('modelFilter',new Set(this.rows.flatMap(r=>(r.totals_by_model_feature||[]).map(x=>x.model)).filter(Boolean)),'All models'); }
  filtered() { const max=this.rows.reduce((a,r)=>a>r.day?a:r.day,'');const days=+document.querySelector('#dateFilter').value;const since=days?new Date(new Date(max+'T00:00:00Z').getTime()-(days-1)*864e5).toISOString().slice(0,10):'';const user=document.querySelector('#userFilter').value,model=document.querySelector('#modelFilter').value;return this.rows.filter(r=>(!since||r.day>=since)&&(user==='all'||(r.user_login||r.User)===user)&&(model==='all'||(r.totals_by_model_feature||[]).some(x=>x.model===model))); }
  filteredBreakdown(rows,key,dimension,metric='code_generation_activity_count') { const out={}, selectedModel=document.querySelector('#modelFilter').value;rows.forEach(r=>(r[key]||[]).forEach(x=>{if(x[dimension] && (dimension!=='model'||selectedModel==='all'||x.model===selectedModel))out[x[dimension]]=(out[x[dimension]]||0)+(+x[metric]||0);}));return out; }
  render() { const rows=this.filtered(), allUsers=new Set(this.rows.map(r=>r.user_login||r.User)).size, active=rows.filter(r=>this.activity(r)>0), activeUsers=new Set(active.map(r=>r.user_login||r.User)).size, users=new Set(rows.map(r=>r.user_login||r.User)).size; const sum=(key)=>rows.reduce((n,r)=>n+(+r[key]||0),0); const agentUsers=new Set(active.filter(r=>r.used_agent).map(r=>r.user_login||r.User)).size,chatUsers=new Set(active.filter(r=>r.used_chat).map(r=>r.user_login||r.User)).size;
    const pct=(a,b)=>b?`${Math.round(a/b*100)}%`:'—';this.set('activeUsers',activeUsers.toLocaleString());this.set('activeUsersNote',`${users.toLocaleString()} reported in selection · ${allUsers.toLocaleString()} in export`);this.set('engagementRate',pct(activeUsers,users));this.set('agentRate',pct(agentUsers,activeUsers));this.set('agentNote',`${agentUsers.toLocaleString()} active people`);this.set('chatRate',pct(chatUsers,activeUsers));this.set('acceptedCode',sum('code_acceptance_activity_count').toLocaleString());this.set('acceptedNote',`${sum('loc_added_sum').toLocaleString()} lines added after Copilot activity`);this.set('creditsUsed',this.format(sum('ai_credits_used')));
    const models=this.filteredBreakdown(rows,'totals_by_model_feature','model'), features=this.filteredBreakdown(rows,'totals_by_feature','feature','user_initiated_interaction_count');const auto=models.auto||0,modelTotal=Object.values(models).reduce((a,b)=>a+b,0);this.set('autoRate',modelTotal?pct(auto,modelTotal)+' Auto':'No model activity');this.set('autoNarrative',modelTotal?`Auto accounts for ${this.format(auto)} of ${this.format(modelTotal)} model-attributed generations. Named-model activity is the remainder.`:'No model-attributed generation was reported.');
    const selectedModel=document.querySelector('#modelFilter').value,byDay={};rows.forEach(r=>{const x=byDay[r.day]||={interactions:0,generation:0,auto:0,named:0};x.interactions+=+r.user_initiated_interaction_count||0;x.generation+=+r.code_generation_activity_count||0;(r.totals_by_model_feature||[]).forEach(m=>{if(selectedModel==='all'||m.model===selectedModel){const amount=+m.code_generation_activity_count||0;if(m.model==='auto')x.auto+=amount;else x.named+=amount;}});byDay[r.day]=x;});const ds=Object.keys(byDay).sort(),mid=Math.ceil(ds.length/2),first=ds.slice(0,mid).reduce((a,d)=>a+byDay[d].interactions,0),last=ds.slice(mid).reduce((a,d)=>a+byDay[d].interactions,0),change=first?Math.round((last-first)/first*100):0;this.set('momentum',ds.length?`${change>=0?'+':''}${change}% interactions`:'—');this.set('momentumNarrative',`Comparing the later half of the selected period with the earlier half.`);const topFeature=this.top(features);this.set('workflow',topFeature?this.label(topFeature[0]):'—');this.set('workflowNarrative',topFeature?`${this.format(topFeature[1])} user-initiated interactions in the leading workflow.`:'No feature activity was reported.');
    this.chart('activityChart','line',{labels:ds,datasets:[{label:'Interactions',data:ds.map(d=>byDay[d].interactions),borderColor:'#83f1c5',backgroundColor:'#83f1c522',fill:true,tension:.35},{label:'Code generation',data:ds.map(d=>byDay[d].generation),borderColor:'#7da8ff',tension:.35}]});this.chart('routingTrendChart','stackedBar',{labels:ds,datasets:[{label:'Auto',data:ds.map(d=>byDay[d].auto),backgroundColor:'#ffb86b'},{label:'Named models',data:ds.map(d=>byDay[d].named),backgroundColor:'#e69cff'}]});this.chart('modelChart','doughnut',this.topN(models));this.chart('featureChart','bar',this.topN(features));this.chart('languageChart','bar',this.topN(this.filteredBreakdown(rows,'totals_by_language_feature','language')));this.chart('ideChart','bar',this.topN(this.filteredBreakdown(rows,'totals_by_ide','ide','user_initiated_interaction_count')));const surfaces={Chat:new Set(),Agent:new Set(),CLI:new Set(),'Coding agent':new Set(),'Cloud agent':new Set(),'Copilot app':new Set()};active.forEach(r=>{const u=r.user_login||r.User;if(r.used_chat)surfaces.Chat.add(u);if(r.used_agent)surfaces.Agent.add(u);if(r.used_cli)surfaces.CLI.add(u);if(r.used_copilot_coding_agent)surfaces['Coding agent'].add(u);if(r.used_copilot_cloud_agent)surfaces['Cloud agent'].add(u);if(r.used_copilot_app)surfaces['Copilot app'].add(u);});this.chart('surfaceChart','bar',{labels:Object.keys(surfaces),values:Object.values(surfaces).map(s=>s.size)});const people={};rows.forEach(r=>{const u=r.user_login||r.User;people[u]=(people[u]||0)+(+r.user_initiated_interaction_count||0)});this.chart('peopleChart','bar',this.topN(people,12));this.renderTable(rows);document.querySelector('#reportTitle').textContent='Copilot activity';document.querySelector('#reportMeta').textContent=ds.length?`${ds[0]} – ${ds.at(-1)} · ${rows.length.toLocaleString()} user/day records`:'No records match these filters'; }
  chart(id,type,data) { if(this.charts[id])this.charts[id].destroy();const canvas=document.querySelector('#'+id);let config;if(type==='line')config={type,data,options:this.options(false,true)};else if(type==='stackedBar'){config={type:'bar',data,options:this.options(false,true)};config.options.scales.x.stacked=true;config.options.scales.y.stacked=true;}else {const labels=data.labels||[],values=data.values||[];config={type,data:{labels,datasets:[{data:values,backgroundColor:['#83f1c5','#7da8ff','#e69cff','#ffb86b','#61d6ed','#a4b5ff','#ff8ea1','#b5d77a','#d7a7ff','#f2d68c','#80c5ad','#eaa3c1']}]},options:this.options(type==='doughnut')};if(type==='bar')config.options.indexAxis='y';}this.charts[id]=new Chart(canvas,config); }
  options(donut,showLegend=donut) { return {responsive:true,maintainAspectRatio:true,plugins:{legend:{display:showLegend,labels:{color:'#b9c6d9',boxWidth:10,font:{size:11}}},tooltip:{callbacks:{label:c=>`${c.label||c.dataset.label}: ${this.format(c.raw??c.parsed.y??c.parsed)}`}}},scales:donut?{}:{x:{ticks:{color:'#8ea0b9',maxRotation:0,autoSkip:true},grid:{color:'#20304a'}},y:{ticks:{color:'#8ea0b9'},grid:{color:'#20304a'},beginAtZero:true}}}; }
  renderTable(rows) { const query=document.querySelector('#tableSearch').value.toLowerCase(), people={};rows.forEach(r=>{const u=r.user_login||r.User;if(!people[u])people[u]={days:0,i:0,g:0,a:0,credits:0,agent:false,chat:false};const p=people[u];p.days++;p.i+=+r.user_initiated_interaction_count||0;p.g+=+r.code_generation_activity_count||0;p.a+=+r.code_acceptance_activity_count||0;p.credits+=+r.ai_credits_used||0;p.agent||=!!r.used_agent;p.chat||=!!r.used_chat;});document.querySelector('#peopleTable').innerHTML=Object.entries(people).filter(([u])=>u.toLowerCase().includes(query)).sort((a,b)=>b[1].i-a[1].i).map(([u,p])=>`<tr><td>${this.escape(u)}</td><td>${p.days}</td><td>${this.format(p.i)}</td><td>${this.format(p.g)}</td><td>${this.format(p.a)}</td><td><span class="badge ${p.agent?'on':''}">${p.agent?'Used':'—'}</span></td><td><span class="badge ${p.chat?'on':''}">${p.chat?'Used':'—'}</span></td><td>${this.format(p.credits)}</td></tr>`).join('')||'<tr><td colspan="8">No people match the current filters.</td></tr>'; }
  activity(r){return(+r.user_initiated_interaction_count||0)+(+r.code_generation_activity_count||0)+(+r.code_acceptance_activity_count||0)} top(o){return Object.entries(o).sort((a,b)=>b[1]-a[1])[0]} topN(o,n=8){const a=Object.entries(o).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,n);return {labels:a.map(x=>this.label(x[0])),values:a.map(x=>x[1])}} label(s){return String(s).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())} set(id,v){document.querySelector('#'+id).textContent=v} format(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:1})} escape(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML} toast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
}
document.addEventListener('DOMContentLoaded',()=>new CopilotSignals());
